### PR TITLE
Add remind functionality

### PR DESCRIPTION
**Pull request by funky-monkey**
Hi, 
I've added the reminder functionality (and updated the docs) from the slack api to your library because I wanted to automate those tasks.

Since this is my first bash script - i'm not sure if i kept to conventions correctly or solved things in the proper way. Also I did not add tests because i dont know how. But I've had fun :)

The only thing I was not able to get right was the `add` functionality. I can't just pass the username because it always returns a `user_not_found` error. I've tried using the `$user` in the same way you did in the curl request, but did not get that right - I always have to pass the `id` of the user to the `add` method. Maybe we can have a discussion on how you solved this? I'd love to learn!

Hope you like this, 

Kind regards, 

Sidney

### CODE REVIEW

**Comment by funky-monkey** [comment]
Is this project still alive?

**Comment by funky-monkey** [comment]
Any update on this?

**Comment by rockymadden** [comment]
My apologies on a the delay. Reviewing now.

**Comment by rockymadden** [comment]
All set, thank you very much! Please see #64. You will receive credit for all your work :)

**Pull request closed without merging**
